name: Build for macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install cmake

      - name: check directory
        run: ls


      - name: Configure CMake
        run: |
          cmake -S . -B build/macos -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build/macos --config Release

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: build/
