name: Build for macOS

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (Debug or Release)'
        required: true
        default: 'Release'
      mode:
        description: 'Configure CMake/build application only/both (c/b/both; defaults to b)'
        required: true
        default: 'b'
  
jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          brew install cmake
          brew install coreutils

      - name: Configure CMake
        if: ${{ inputs.mode == 'c' || inputs.mode == 'both'}}
        run: |
          cmake -S app/src/main/cpp -B builds/macos -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}

      - name: Build project
        if: ${{ inputs.mode == 'b' || inputs.mode == 'both'}}
        run: cmake --build builds/macos --config ${{ inputs.build_type }}

      - name: Run tests / execute built app
        if: ${{ inputs.mode == 'b' || inputs.mode == 'both'}}
        run: |
          cd builds/macos
          gtimeout -k 5s 20s ./iLuma

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: builds/macos
