name: Build for macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (Release or Debug)'
        required: true
        default: 'Release'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install cmake

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build_type }}

      - name: Build project
        run: cmake --build build --config ${{ github.event.inputs.build_type }}

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: macos-${{ github.event.inputs.build_type }}-build
          path: build/
