name: Build for iOS

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (Debug or Release)'
        required: true
        default: 'Release'
      mode:
        description: 'Configure CMake/build application only/both (c/b/both; defaults to b)'
        required: true
        default: 'b'

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: brew install cmake ninja

      - name: Set SDK Path
        id: set-sdk
        run: echo "sdk_path=$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_OUTPUT

      - name: Configure CMake
        if: ${{ inputs.mode == 'c' || inputs.mode == 'both' }}
        run: |
          cmake -S app/src/main/cpp -B builds/ios \
            -G Xcode \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} \
            -DIOS=ON \
            -DDOWNLOAD_DEPENDENCIES=ON \
            -DCMAKE_OSX_SYSROOT=${{ steps.set-sdk.outputs.sdk_path }} \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DEFFECTIVE_PLATFORM_NAME=-iphoneos \
            -Wdev -Wdeprecated -Werror


      - name: Build project
        if: ${{ inputs.mode == 'b' || inputs.mode == 'both' }}
        env:
          SDKROOT: ${{ steps.set-sdk.outputs.sdk_path }}
          EFFECTIVE_PLATFORM_NAME: -iphoneos
        run: |
          cmake --build builds/ios --config ${{ inputs.build_type }} -- \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: iOS
          path: builds/ios
